"""baseline full schema sec2.3

Revision ID: 8026647f94d5
Revises: 
Create Date: 2026-06-28 21:35:46.622396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8026647f94d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarantined_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quarantine_chatid', 'quarantined_messages', ['chat_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=True),
    sa.Column('phase', sa.String(length=255), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cards_latest', 'cards', ['latest_at'], unique=False)
    op.create_index('idx_cards_project_phase', 'cards', ['project_id', 'phase'], unique=False)
    op.create_index(op.f('ix_cards_project_id'), 'cards', ['project_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('external_chat_id', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), server_default='Chat purpose not yet defined.', nullable=False),
    sa.Column('phase', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_project_id'), 'chats', ['project_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_project_id'), 'join_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_email'), 'join_requests', ['user_email'], unique=False)
    op.create_table('project_activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_activity_logs_actor_email'), 'project_activity_logs', ['actor_email'], unique=False)
    op.create_index(op.f('ix_project_activity_logs_project_id'), 'project_activity_logs', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_email'), 'project_members', ['user_email'], unique=False)
    op.create_table('card_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('reverted_from_version_id', sa.String(), nullable=True),
    sa.Column('source_refs', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_versions_card_id'), 'card_versions', ['card_id'], unique=False)
    op.create_table('synthesis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('reply_group_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'reply_group_id', name='uq_chat_replygroup')
    )
    op.create_index(op.f('ix_synthesis_chat_id'), 'synthesis', ['chat_id'], unique=False)
    op.create_index(op.f('ix_synthesis_reply_group_id'), 'synthesis', ['reply_group_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('synthesis_id', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synthesis_id'], ['synthesis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_chat_id'), 'knowledge_nodes', ['chat_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_section'), 'knowledge_nodes', ['section'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_synthesis_id'), 'knowledge_nodes', ['synthesis_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('include_in_summary', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reply_group_id', sa.String(length=100), nullable=True),
    sa.Column('signal_level', sa.String(length=20), nullable=True),
    sa.Column('synthesis_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synthesis_id'], ['synthesis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chatid_createdat', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_group_id'), 'messages', ['reply_group_id'], unique=False)
    op.create_index(op.f('ix_messages_synthesis_id'), 'messages', ['synthesis_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('from_node_id', sa.String(), nullable=True),
    sa.Column('to_node_id', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_chat_id'), 'knowledge_edges', ['chat_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_from_node_id'), 'knowledge_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_relation'), 'knowledge_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_to_node_id'), 'knowledge_edges', ['to_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_edges_to_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_relation'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_from_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_chat_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_messages_synthesis_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_group_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_messages_chatid_createdat', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_nodes_synthesis_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_section'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_chat_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_synthesis_reply_group_id'), table_name='synthesis')
    op.drop_index(op.f('ix_synthesis_chat_id'), table_name='synthesis')
    op.drop_table('synthesis')
    op.drop_index(op.f('ix_card_versions_card_id'), table_name='card_versions')
    op.drop_table('card_versions')
    op.drop_index(op.f('ix_project_members_user_email'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_activity_logs_project_id'), table_name='project_activity_logs')
    op.drop_index(op.f('ix_project_activity_logs_actor_email'), table_name='project_activity_logs')
    op.drop_table('project_activity_logs')
    op.drop_index(op.f('ix_join_requests_user_email'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_project_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_chats_project_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_cards_project_id'), table_name='cards')
    op.drop_index('idx_cards_project_phase', table_name='cards')
    op.drop_index('idx_cards_latest', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_quarantine_chatid', table_name='quarantined_messages')
    op.drop_table('quarantined_messages')
    op.drop_table('projects')
    # ### end Alembic commands ###
